<template>
  <v-app id="inspire">
    <v-navigation-drawer v-model="drawer" :clipped="$vuetify.breakpoint.lgAndUp" fixed app>
      <v-list dense>
        <template v-for="item in items">
          <v-layout v-if="item.heading" :key="item.heading" row align-center>
            <v-flex xs6>
              <v-subheader v-if="item.heading">
                {{ item.heading }}
              </v-subheader>
            </v-flex>
          </v-layout>
          <v-list-group v-else-if="item.children" :key="item.text" v-model="item.model"
            :prepend-icon="item.model ? item.icon : item['icon-alt']" append-icon="">
            <template v-slot:activator>
              <v-list-tile v-ripple>
                <v-list-tile-content v-ripple>
                  <v-list-tile-title>
                    {{ item.text }}
                  </v-list-tile-title>
                </v-list-tile-content>
              </v-list-tile>
            </template>
            <v-list-tile v-for="(child, i) in item.children" :key="i" v-ripple>
              <v-list-tile-action v-if="child.render &&child.icon" :to="child.to">
                <v-icon>{{ child.icon }}</v-icon>
              </v-list-tile-action>
              <v-list-tile-content v-if="child.render">
                <v-list-tile-title>
                  {{ child.text }}
                </v-list-tile-title>
              </v-list-tile-content>
            </v-list-tile>
          </v-list-group>
          <v-list-tile :to="item.to" v-else :key="item.text">
            <v-list-tile-action v-if="item.render">
              <v-icon>{{ item.icon }}</v-icon>
            </v-list-tile-action>
            <v-list-tile-content>
              <v-list-tile-title v-if="item.render">
                {{ item.text }}
              </v-list-tile-title>
            </v-list-tile-content>
          </v-list-tile>
        </template>
      </v-list>
    </v-navigation-drawer>
    <v-toolbar :clipped-left="$vuetify.breakpoint.lgAndUp" color="#7EC0EE" light app fixed>
      <v-toolbar-title style="width: 300px" class="ml-0 pl-3">
        <v-toolbar-side-icon @click.stop="drawer = !drawer"></v-toolbar-side-icon>
        <span class="hidden-sm-and-down">XHUMA</span>
      </v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn icon large>
        <v-avatar size="32px" tile>
          <img height="400px" width="400px" src="http://assets.stickpng.com/thumbs/59b5bc2a6dbe923c39853e02.png">
        </v-avatar>
      </v-btn>
    </v-toolbar>
    <main>
      <v-content>
        <v-container fluid fill-height>
          <v-layout justify-center align-center>
            <v-flex>
              <router-view></router-view>
            </v-flex>
          </v-layout>
          <v-tooltip top>
            <template v-slot:activator="{ on }">
              <v-btn bottom color="skyblue" v-ripple dark fab fixed right @click="dialog=true" v-on="on">
                <v-icon>person_add</v-icon>
              </v-btn>
            </template>
            <span>Login/SignUp</span>
          </v-tooltip>
        </v-container>
      </v-content>
    </main>
    <template>
      <div class="text-center">
        <v-dialog v-model="dialog" width="500">
          <v-card>
            <v-card-title>
              Login in to Xhuma
            </v-card-title>
            <v-tabs v-model="tab" color="#7EC0EE" centered dark icons-and-text>
              <v-tabs-slider></v-tabs-slider>
              <v-tab href="#tab-1">
                Login Existing Wallet
                <v-icon>donut_large</v-icon>
              </v-tab>
              <v-tab href="#tab-2">
                Create New Wallet Address
                <v-icon>add_box</v-icon>
              </v-tab>
            </v-tabs>
            <v-divider></v-divider>
            <v-tabs-items v-model="tab">
              <v-tab-item value='tab-2'>
                <v-card>
                  <v-card-title class="headline grey lighten-3">Terms and Conditions</v-card-title>
                  <v-card-text>
                    <b>USER REGISTRATION</b>
                    <br>
                    <br>
                    Please ensure that you do not share your <a
                      href="https://vomtom.at/ethereum-private-and-public-keys/"> private key</a> generated by the
                    website as this could render
                    your account vulnerable
                    we will not in any way share your private key with the public but the public will be able to view
                    your <a href="https://vomtom.at/ethereum-private-and-public-keys/"> public key</a>
                    <br><br>
                    <b> PROHIBITED ACTIVITIES</b>
                    <br><br>
                    You may not access or use the Site for any purpose other than that for which we make the Site
                    available. The Site may not be used in connection with any commercial endeavors except those that
                    are specifically endorsed or approved by us.
                    <br><br>
                    <b>As a user of the Site, you agree not to:</b>
                    <br><br>
                    1. systematically retrieve data or other content from the Site to create or compile, directly or
                    indirectly, a collection, compilation, database, or directory without written permission from
                    us.<br>
                    2. make any unauthorized use of the Site, including collecting usernames and/or email addresses
                    of
                    users by electronic or other means for the purpose of sending unsolicited email, or creating
                    user
                    accounts by automated means or under false pretenses.<br>
                    3. use a buying agent or purchasing agent to make purchases on the Site.<br>
                    4. use the Site to advertise or offer to sell goods and services.<br>
                    5. circumvent, disable, or otherwise interfere with security-related features of the Site,
                    including
                    features that prevent or restrict the use or copying of any Content or enforce limitations on
                    the
                    use of the Site and/or the Content contained therein.<br>
                    6. engage in unauthorized framing of or linking to the Site.<br>

                  </v-card-text>
                </v-card>
                <v-card-actions>
                  <v-spacer></v-spacer>
                  <v-btn color="primary" v-ripple text @click="dialog = false; login(true)">
                    Create
                  </v-btn>
                </v-card-actions>
              </v-tab-item>
              <v-tab-item value='tab-1'>
                <v-form ref="form" v-model="valid" :lazy-validation="lazy">
                  <v-card flat align-center justify-center row fill-height>
                    <v-text-field label="Private Key" hint="e.g. 832eaaaaaa..." v-model="privateKey"
                      :rules="privateKeyRules"></v-text-field>
                  </v-card>
                  <v-card-actions>
                    <v-spacer></v-spacer>
                    <v-btn v-ripple :disabled="!valid" color="success" class="mr-4" @click="validate;login(false)">
                      Login
                    </v-btn>
                  </v-card-actions>
                </v-form>
              </v-tab-item>
            </v-tabs-items>
            <loading :active.sync="isLoading" :can-cancel="false" :is-full-page="fullPage">
            </loading>
          </v-card>
        </v-dialog>
      </div>
    </template>
  </v-app>
</template>

<script>
  import Loading from 'vue-loading-overlay';

  import Portis from "@portis/web3";
  import Web3 from 'web3';
  import EmbarkJS from "../embarkArtifacts/embarkjs";
  import Swal from 'sweetalert2'
  import SecureLS from 'secure-ls'
  import {
    setInterval,
    clearInterval
  } from 'timers';
  export default {
    components: {
      Loading
    },
    data() {
      return {
        fullPage: true,
        privateKey: '',
        lazy: false,
        privateKeyRules: [
          v => !!v || 'Private Key is required',
          v => (v && v.length === 64) || 'Private Key must have 64 characters',
        ],
        dialog: false,
        drawer: null,
        fullPage: true,
        isLoading: false,
        items: [{
          icon: 'find_in_page',
          text: 'View Connected Schools',
          to: "/Landing",
          render: true
        }],
        Portis: null,
        web3: null,
        localNode: {
          nodeUrl: 'http://localhost:11000',
          chainId: 1234,
        },
        loggedIn: false,
        SecureLS: new SecureLS(),
        tab: null,
        loginRequest: false,
        valid: true
      }
    },
    mounted() {
      console.log(EmbarkJS.Providers)
      // EmbarkJS.onReady((err) => {
      console.log(EmbarkJS)
      this.Portis = new Portis('0705023c-3e90-405e-a0c3-6ab9ad4be7ed', this.localNode, {
        scope: ["email"]
      }, true);
      this.Portis.config.registerPageByDefault = false
      console.log(this.Portis.config.registerPageByDefault)
      this.web3 = new Web3(this.Portis.provider);
      EmbarkJS.Providers = this.web3
      EmbarkJS.Providers.eth.getBlockNumber().then((block) => {
        console.log(block)
      })
      this.watchForAccountChanges()

      //     })
    },
    props: {
      source: String
    },
    beforeMount() {
      this.checkUserType();
    },
    methods: {
      checkUserType() {
        var toPush = [{
          icon: 'border_color',
          text: 'Register Schools',
          to: "/RegisterSchools",
          render: true
        }]
        toPush.forEach(menuItem => {
          this.items.push(menuItem)
        });
      },
      watchForAccountChanges() {
        let tempThis = this
        window.ethereum.on('accountsChanged', function (accounts) {
          location.reload()
        })
        window.ethereum.on('networkChanged', function (netId) {
          location.reload()
        })
        window.ethereum.on('networkChanged', function (netId) {
          location.reload()
        })
      },
      errorWithFooter(footerMessage, text) {
        Swal.fire({
          type: 'error',
          title: 'OH Noo',
          text: text,
          footer: footerMessage
        })
      },
      error(message) {
        Swal.fire({
          type: 'error',
          title: 'Oops...',
          text: message,
          allowOutsideClick: true
        })
      },
      success(message) {
        this.$snotify.success(message, {
          timeout: 2000,
          showProgressBar: false,
          closeOnClick: false,
          pauseOnHover: true
        })
      },
      login(isNew) {
        this.loginRequest = true
        this.isLoading = true
        if (isNew) {
          this.Portis.importWallet(this.privateKey).then((results, error) => {
            console.log(error, results)
          }).catch((err) => {
            console.log(error)
          });
        } else {
          this.Portis.showPortis()
        }
        console.log(this.Portis)
        this.Portis.onLogin((walletAddress, email) => {
          this.SecureLS.set('loggedIn', true);
          this.SecureLS.set('walletAddress', walletAddress);
          this.SecureLS.set('emailAddress', email);
          this.isLoading = false
        })
        this.Portis.onLogout(() => {
          console.log('User logged out');
          this.SecureLS.removeAll()
        });
      },
      validate() {
        if (this.$refs.form.validate()) {
          this.snackbar = true
        }
      },
      reset() {
        this.$refs.form.reset()
      },
      resetValidation() {
        this.$refs.form.resetValidation()
      }

    }
  }
</script>